/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterRouteImport } from './routes/master'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminEditorLayoutRouteImport } from './routes/admin.editor-layout'
import { Route as AdminEstatisticasRouteImport } from './routes/admin.estatisticas'
import { Route as AdminFinancasRouteImport } from './routes/admin.financas'
import { Route as AdminHistoricoRouteImport } from './routes/admin.historico'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminPreviewRouteImport } from './routes/admin.preview'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminVenderRouteImport } from './routes/admin.vender'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as MasterIndexRouteImport } from './routes/master.index'
import { Route as MasterAssinaturasRouteImport } from './routes/master.assinaturas'
import { Route as MasterConfiguracoesRouteImport } from './routes/master.configuracoes'
import { Route as MasterLoginRouteImport } from './routes/master.login'
import { Route as MasterLojasRouteImport } from './routes/master.lojas'
import { Route as MasterPlanosRouteImport } from './routes/master.planos'
import { Route as MasterUsuariosRouteImport } from './routes/master.usuarios'
import { Route as AdminHistoricoIndexRouteImport } from './routes/admin.historico.index'
import { Route as AdminHistoricoIdRouteImport } from './routes/admin.historico.$id'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin.pedidos.index'
import { Route as AdminPedidosIdRouteImport } from './routes/admin.pedidos.$id'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin.produtos.index'
import { Route as AdminProdutosIdRouteImport } from './routes/admin.produtos.$id'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin.produtos.novo'
import { Route as LojaSlugIndexRouteImport } from './routes/loja.$slug.index'
import { Route as LojaSlugCheckoutRouteImport } from './routes/loja.$slug.checkout'
import { Route as LojaSlugContatoRouteImport } from './routes/loja.$slug.contato'
import { Route as LojaSlugEntrarRouteImport } from './routes/loja.$slug.entrar'
import { Route as LojaSlugMinhaContaRouteImport } from './routes/loja.$slug.minha-conta'
import { Route as LojaSlugQuemSomosRouteImport } from './routes/loja.$slug.quem-somos'
import { Route as LojaSlugCategoriaCategorySlugRouteImport } from './routes/loja.$slug.categoria.$categorySlug'
import { Route as LojaSlugProdutoIdRouteImport } from './routes/loja.$slug.produto.$id'
import { Route as LojaSlugCategoriaCategorySlugChildSlugRouteImport } from './routes/loja.$slug.categoria.$categorySlug.$childSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorLayoutRoute = AdminEditorLayoutRouteImport.update({
  id: '/editor-layout',
  path: '/editor-layout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstatisticasRoute = AdminEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancasRoute = AdminFinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoricoRoute = AdminHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVenderRoute = AdminVenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => AdminRoute,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRoute = MasterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasterRoute,
} as any)
const MasterAssinaturasRoute = MasterAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => MasterRoute,
} as any)
const MasterConfiguracoesRoute = MasterConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => MasterRoute,
} as any)
const MasterLoginRoute = MasterLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MasterRoute,
} as any)
const MasterLojasRoute = MasterLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => MasterRoute,
} as any)
const MasterPlanosRoute = MasterPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => MasterRoute,
} as any)
const MasterUsuariosRoute = MasterUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => MasterRoute,
} as any)
const AdminHistoricoIndexRoute = AdminHistoricoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminHistoricoRoute,
} as any)
const AdminHistoricoIdRoute = AdminHistoricoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminHistoricoRoute,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPedidosRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPedidosRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const LojaSlugIndexRoute = LojaSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugCheckoutRoute = LojaSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugContatoRoute = LojaSlugContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugEntrarRoute = LojaSlugEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugMinhaContaRoute = LojaSlugMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugQuemSomosRoute = LojaSlugQuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugCategoriaCategorySlugRoute =
  LojaSlugCategoriaCategorySlugRouteImport.update({
    id: '/categoria/$categorySlug',
    path: '/categoria/$categorySlug',
    getParentRoute: () => LojaSlugRoute,
  } as any)
const LojaSlugProdutoIdRoute = LojaSlugProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugCategoriaCategorySlugChildSlugRoute =
  LojaSlugCategoriaCategorySlugChildSlugRouteImport.update({
    id: '/$childSlug',
    path: '/$childSlug',
    getParentRoute: () => LojaSlugCategoriaCategorySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/editor-layout': typeof AdminEditorLayoutRoute
  '/admin/estatisticas': typeof AdminEstatisticasRoute
  '/admin/financas': typeof AdminFinancasRoute
  '/admin/historico': typeof AdminHistoricoRouteWithChildren
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vender': typeof AdminVenderRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/login': typeof MasterLoginRoute
  '/master/lojas': typeof MasterLojasRoute
  '/master/planos': typeof MasterPlanosRoute
  '/master/usuarios': typeof MasterUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/master/': typeof MasterIndexRoute
  '/admin/historico/$id': typeof AdminHistoricoIdRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/loja/$slug/checkout': typeof LojaSlugCheckoutRoute
  '/loja/$slug/contato': typeof LojaSlugContatoRoute
  '/loja/$slug/entrar': typeof LojaSlugEntrarRoute
  '/loja/$slug/minha-conta': typeof LojaSlugMinhaContaRoute
  '/loja/$slug/quem-somos': typeof LojaSlugQuemSomosRoute
  '/admin/historico/': typeof AdminHistoricoIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/loja/$slug/categoria/$categorySlug': typeof LojaSlugCategoriaCategorySlugRouteWithChildren
  '/loja/$slug/produto/$id': typeof LojaSlugProdutoIdRoute
  '/loja/$slug/categoria/$categorySlug/$childSlug': typeof LojaSlugCategoriaCategorySlugChildSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/editor-layout': typeof AdminEditorLayoutRoute
  '/admin/estatisticas': typeof AdminEstatisticasRoute
  '/admin/financas': typeof AdminFinancasRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vender': typeof AdminVenderRoute
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/login': typeof MasterLoginRoute
  '/master/lojas': typeof MasterLojasRoute
  '/master/planos': typeof MasterPlanosRoute
  '/master/usuarios': typeof MasterUsuariosRoute
  '/admin': typeof AdminIndexRoute
  '/master': typeof MasterIndexRoute
  '/admin/historico/$id': typeof AdminHistoricoIdRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/loja/$slug/checkout': typeof LojaSlugCheckoutRoute
  '/loja/$slug/contato': typeof LojaSlugContatoRoute
  '/loja/$slug/entrar': typeof LojaSlugEntrarRoute
  '/loja/$slug/minha-conta': typeof LojaSlugMinhaContaRoute
  '/loja/$slug/quem-somos': typeof LojaSlugQuemSomosRoute
  '/admin/historico': typeof AdminHistoricoIndexRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
  '/loja/$slug': typeof LojaSlugIndexRoute
  '/loja/$slug/categoria/$categorySlug': typeof LojaSlugCategoriaCategorySlugRouteWithChildren
  '/loja/$slug/produto/$id': typeof LojaSlugProdutoIdRoute
  '/loja/$slug/categoria/$categorySlug/$childSlug': typeof LojaSlugCategoriaCategorySlugChildSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/master': typeof MasterRouteWithChildren
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/editor-layout': typeof AdminEditorLayoutRoute
  '/admin/estatisticas': typeof AdminEstatisticasRoute
  '/admin/financas': typeof AdminFinancasRoute
  '/admin/historico': typeof AdminHistoricoRouteWithChildren
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/preview': typeof AdminPreviewRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vender': typeof AdminVenderRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/master/assinaturas': typeof MasterAssinaturasRoute
  '/master/configuracoes': typeof MasterConfiguracoesRoute
  '/master/login': typeof MasterLoginRoute
  '/master/lojas': typeof MasterLojasRoute
  '/master/planos': typeof MasterPlanosRoute
  '/master/usuarios': typeof MasterUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/master/': typeof MasterIndexRoute
  '/admin/historico/$id': typeof AdminHistoricoIdRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/loja/$slug/checkout': typeof LojaSlugCheckoutRoute
  '/loja/$slug/contato': typeof LojaSlugContatoRoute
  '/loja/$slug/entrar': typeof LojaSlugEntrarRoute
  '/loja/$slug/minha-conta': typeof LojaSlugMinhaContaRoute
  '/loja/$slug/quem-somos': typeof LojaSlugQuemSomosRoute
  '/admin/historico/': typeof AdminHistoricoIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/loja/$slug/categoria/$categorySlug': typeof LojaSlugCategoriaCategorySlugRouteWithChildren
  '/loja/$slug/produto/$id': typeof LojaSlugProdutoIdRoute
  '/loja/$slug/categoria/$categorySlug/$childSlug': typeof LojaSlugCategoriaCategorySlugChildSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/master'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/editor-layout'
    | '/admin/estatisticas'
    | '/admin/financas'
    | '/admin/historico'
    | '/admin/onboarding'
    | '/admin/pedidos'
    | '/admin/preview'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/admin/vender'
    | '/loja/$slug'
    | '/master/assinaturas'
    | '/master/configuracoes'
    | '/master/login'
    | '/master/lojas'
    | '/master/planos'
    | '/master/usuarios'
    | '/admin/'
    | '/master/'
    | '/admin/historico/$id'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/loja/$slug/checkout'
    | '/loja/$slug/contato'
    | '/loja/$slug/entrar'
    | '/loja/$slug/minha-conta'
    | '/loja/$slug/quem-somos'
    | '/admin/historico/'
    | '/admin/pedidos/'
    | '/admin/produtos/'
    | '/loja/$slug/'
    | '/loja/$slug/categoria/$categorySlug'
    | '/loja/$slug/produto/$id'
    | '/loja/$slug/categoria/$categorySlug/$childSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/editor-layout'
    | '/admin/estatisticas'
    | '/admin/financas'
    | '/admin/onboarding'
    | '/admin/preview'
    | '/admin/usuarios'
    | '/admin/vender'
    | '/master/assinaturas'
    | '/master/configuracoes'
    | '/master/login'
    | '/master/lojas'
    | '/master/planos'
    | '/master/usuarios'
    | '/admin'
    | '/master'
    | '/admin/historico/$id'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/loja/$slug/checkout'
    | '/loja/$slug/contato'
    | '/loja/$slug/entrar'
    | '/loja/$slug/minha-conta'
    | '/loja/$slug/quem-somos'
    | '/admin/historico'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/loja/$slug'
    | '/loja/$slug/categoria/$categorySlug'
    | '/loja/$slug/produto/$id'
    | '/loja/$slug/categoria/$categorySlug/$childSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/master'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/editor-layout'
    | '/admin/estatisticas'
    | '/admin/financas'
    | '/admin/historico'
    | '/admin/onboarding'
    | '/admin/pedidos'
    | '/admin/preview'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/admin/vender'
    | '/loja/$slug'
    | '/master/assinaturas'
    | '/master/configuracoes'
    | '/master/login'
    | '/master/lojas'
    | '/master/planos'
    | '/master/usuarios'
    | '/admin/'
    | '/master/'
    | '/admin/historico/$id'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/loja/$slug/checkout'
    | '/loja/$slug/contato'
    | '/loja/$slug/entrar'
    | '/loja/$slug/minha-conta'
    | '/loja/$slug/quem-somos'
    | '/admin/historico/'
    | '/admin/pedidos/'
    | '/admin/produtos/'
    | '/loja/$slug/'
    | '/loja/$slug/categoria/$categorySlug'
    | '/loja/$slug/produto/$id'
    | '/loja/$slug/categoria/$categorySlug/$childSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRouteWithChildren
  LojaSlugRoute: typeof LojaSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editor-layout': {
      id: '/admin/editor-layout'
      path: '/editor-layout'
      fullPath: '/admin/editor-layout'
      preLoaderRoute: typeof AdminEditorLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estatisticas': {
      id: '/admin/estatisticas'
      path: '/estatisticas'
      fullPath: '/admin/estatisticas'
      preLoaderRoute: typeof AdminEstatisticasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financas': {
      id: '/admin/financas'
      path: '/financas'
      fullPath: '/admin/financas'
      preLoaderRoute: typeof AdminFinancasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/historico': {
      id: '/admin/historico'
      path: '/historico'
      fullPath: '/admin/historico'
      preLoaderRoute: typeof AdminHistoricoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preview': {
      id: '/admin/preview'
      path: '/preview'
      fullPath: '/admin/preview'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vender': {
      id: '/admin/vender'
      path: '/vender'
      fullPath: '/admin/vender'
      preLoaderRoute: typeof AdminVenderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof MasterIndexRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/assinaturas': {
      id: '/master/assinaturas'
      path: '/assinaturas'
      fullPath: '/master/assinaturas'
      preLoaderRoute: typeof MasterAssinaturasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/configuracoes': {
      id: '/master/configuracoes'
      path: '/configuracoes'
      fullPath: '/master/configuracoes'
      preLoaderRoute: typeof MasterConfiguracoesRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/login': {
      id: '/master/login'
      path: '/login'
      fullPath: '/master/login'
      preLoaderRoute: typeof MasterLoginRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/lojas': {
      id: '/master/lojas'
      path: '/lojas'
      fullPath: '/master/lojas'
      preLoaderRoute: typeof MasterLojasRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/planos': {
      id: '/master/planos'
      path: '/planos'
      fullPath: '/master/planos'
      preLoaderRoute: typeof MasterPlanosRouteImport
      parentRoute: typeof MasterRoute
    }
    '/master/usuarios': {
      id: '/master/usuarios'
      path: '/usuarios'
      fullPath: '/master/usuarios'
      preLoaderRoute: typeof MasterUsuariosRouteImport
      parentRoute: typeof MasterRoute
    }
    '/admin/historico/': {
      id: '/admin/historico/'
      path: '/'
      fullPath: '/admin/historico/'
      preLoaderRoute: typeof AdminHistoricoIndexRouteImport
      parentRoute: typeof AdminHistoricoRoute
    }
    '/admin/historico/$id': {
      id: '/admin/historico/$id'
      path: '/$id'
      fullPath: '/admin/historico/$id'
      preLoaderRoute: typeof AdminHistoricoIdRouteImport
      parentRoute: typeof AdminHistoricoRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/loja/$slug/': {
      id: '/loja/$slug/'
      path: '/'
      fullPath: '/loja/$slug/'
      preLoaderRoute: typeof LojaSlugIndexRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/checkout': {
      id: '/loja/$slug/checkout'
      path: '/checkout'
      fullPath: '/loja/$slug/checkout'
      preLoaderRoute: typeof LojaSlugCheckoutRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/contato': {
      id: '/loja/$slug/contato'
      path: '/contato'
      fullPath: '/loja/$slug/contato'
      preLoaderRoute: typeof LojaSlugContatoRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/entrar': {
      id: '/loja/$slug/entrar'
      path: '/entrar'
      fullPath: '/loja/$slug/entrar'
      preLoaderRoute: typeof LojaSlugEntrarRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/minha-conta': {
      id: '/loja/$slug/minha-conta'
      path: '/minha-conta'
      fullPath: '/loja/$slug/minha-conta'
      preLoaderRoute: typeof LojaSlugMinhaContaRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/quem-somos': {
      id: '/loja/$slug/quem-somos'
      path: '/quem-somos'
      fullPath: '/loja/$slug/quem-somos'
      preLoaderRoute: typeof LojaSlugQuemSomosRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/categoria/$categorySlug': {
      id: '/loja/$slug/categoria/$categorySlug'
      path: '/categoria/$categorySlug'
      fullPath: '/loja/$slug/categoria/$categorySlug'
      preLoaderRoute: typeof LojaSlugCategoriaCategorySlugRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/produto/$id': {
      id: '/loja/$slug/produto/$id'
      path: '/produto/$id'
      fullPath: '/loja/$slug/produto/$id'
      preLoaderRoute: typeof LojaSlugProdutoIdRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/categoria/$categorySlug/$childSlug': {
      id: '/loja/$slug/categoria/$categorySlug/$childSlug'
      path: '/$childSlug'
      fullPath: '/loja/$slug/categoria/$categorySlug/$childSlug'
      preLoaderRoute: typeof LojaSlugCategoriaCategorySlugChildSlugRouteImport
      parentRoute: typeof LojaSlugCategoriaCategorySlugRoute
    }
  }
}

interface AdminHistoricoRouteChildren {
  AdminHistoricoIdRoute: typeof AdminHistoricoIdRoute
  AdminHistoricoIndexRoute: typeof AdminHistoricoIndexRoute
}

const AdminHistoricoRouteChildren: AdminHistoricoRouteChildren = {
  AdminHistoricoIdRoute: AdminHistoricoIdRoute,
  AdminHistoricoIndexRoute: AdminHistoricoIndexRoute,
}

const AdminHistoricoRouteWithChildren = AdminHistoricoRoute._addFileChildren(
  AdminHistoricoRouteChildren,
)

interface AdminPedidosRouteChildren {
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
}

const AdminPedidosRouteChildren: AdminPedidosRouteChildren = {
  AdminPedidosIdRoute: AdminPedidosIdRoute,
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
}

const AdminPedidosRouteWithChildren = AdminPedidosRoute._addFileChildren(
  AdminPedidosRouteChildren,
)

interface AdminProdutosRouteChildren {
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
}

const AdminProdutosRouteChildren: AdminProdutosRouteChildren = {
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
}

const AdminProdutosRouteWithChildren = AdminProdutosRoute._addFileChildren(
  AdminProdutosRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEditorLayoutRoute: typeof AdminEditorLayoutRoute
  AdminEstatisticasRoute: typeof AdminEstatisticasRoute
  AdminFinancasRoute: typeof AdminFinancasRoute
  AdminHistoricoRoute: typeof AdminHistoricoRouteWithChildren
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminPedidosRoute: typeof AdminPedidosRouteWithChildren
  AdminPreviewRoute: typeof AdminPreviewRoute
  AdminProdutosRoute: typeof AdminProdutosRouteWithChildren
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminVenderRoute: typeof AdminVenderRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEditorLayoutRoute: AdminEditorLayoutRoute,
  AdminEstatisticasRoute: AdminEstatisticasRoute,
  AdminFinancasRoute: AdminFinancasRoute,
  AdminHistoricoRoute: AdminHistoricoRouteWithChildren,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminPedidosRoute: AdminPedidosRouteWithChildren,
  AdminPreviewRoute: AdminPreviewRoute,
  AdminProdutosRoute: AdminProdutosRouteWithChildren,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminVenderRoute: AdminVenderRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MasterRouteChildren {
  MasterAssinaturasRoute: typeof MasterAssinaturasRoute
  MasterConfiguracoesRoute: typeof MasterConfiguracoesRoute
  MasterLoginRoute: typeof MasterLoginRoute
  MasterLojasRoute: typeof MasterLojasRoute
  MasterPlanosRoute: typeof MasterPlanosRoute
  MasterUsuariosRoute: typeof MasterUsuariosRoute
  MasterIndexRoute: typeof MasterIndexRoute
}

const MasterRouteChildren: MasterRouteChildren = {
  MasterAssinaturasRoute: MasterAssinaturasRoute,
  MasterConfiguracoesRoute: MasterConfiguracoesRoute,
  MasterLoginRoute: MasterLoginRoute,
  MasterLojasRoute: MasterLojasRoute,
  MasterPlanosRoute: MasterPlanosRoute,
  MasterUsuariosRoute: MasterUsuariosRoute,
  MasterIndexRoute: MasterIndexRoute,
}

const MasterRouteWithChildren =
  MasterRoute._addFileChildren(MasterRouteChildren)

interface LojaSlugCategoriaCategorySlugRouteChildren {
  LojaSlugCategoriaCategorySlugChildSlugRoute: typeof LojaSlugCategoriaCategorySlugChildSlugRoute
}

const LojaSlugCategoriaCategorySlugRouteChildren: LojaSlugCategoriaCategorySlugRouteChildren =
  {
    LojaSlugCategoriaCategorySlugChildSlugRoute:
      LojaSlugCategoriaCategorySlugChildSlugRoute,
  }

const LojaSlugCategoriaCategorySlugRouteWithChildren =
  LojaSlugCategoriaCategorySlugRoute._addFileChildren(
    LojaSlugCategoriaCategorySlugRouteChildren,
  )

interface LojaSlugRouteChildren {
  LojaSlugCheckoutRoute: typeof LojaSlugCheckoutRoute
  LojaSlugContatoRoute: typeof LojaSlugContatoRoute
  LojaSlugEntrarRoute: typeof LojaSlugEntrarRoute
  LojaSlugMinhaContaRoute: typeof LojaSlugMinhaContaRoute
  LojaSlugQuemSomosRoute: typeof LojaSlugQuemSomosRoute
  LojaSlugIndexRoute: typeof LojaSlugIndexRoute
  LojaSlugCategoriaCategorySlugRoute: typeof LojaSlugCategoriaCategorySlugRouteWithChildren
  LojaSlugProdutoIdRoute: typeof LojaSlugProdutoIdRoute
}

const LojaSlugRouteChildren: LojaSlugRouteChildren = {
  LojaSlugCheckoutRoute: LojaSlugCheckoutRoute,
  LojaSlugContatoRoute: LojaSlugContatoRoute,
  LojaSlugEntrarRoute: LojaSlugEntrarRoute,
  LojaSlugMinhaContaRoute: LojaSlugMinhaContaRoute,
  LojaSlugQuemSomosRoute: LojaSlugQuemSomosRoute,
  LojaSlugIndexRoute: LojaSlugIndexRoute,
  LojaSlugCategoriaCategorySlugRoute:
    LojaSlugCategoriaCategorySlugRouteWithChildren,
  LojaSlugProdutoIdRoute: LojaSlugProdutoIdRoute,
}

const LojaSlugRouteWithChildren = LojaSlugRoute._addFileChildren(
  LojaSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRouteWithChildren,
  LojaSlugRoute: LojaSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
