// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwowgtuurjlwatvfiefe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3b3dndHV1cmpsd2F0dmZpZWZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ2NDI3MjcsImV4cCI6MjEwMDIxODcyN30.5Xu2VMNBlcVRMvgWbZ2G2DJKPey2oXOlSi1iDWWi2ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});